name: Infra deploy
on:
  push:
    paths:
      - 'infra/general/*'

jobs:
  sls-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.4.1
      - uses: actions/checkout@v2

      - name: Install serverless # we can use serverless action in the future to skip this step
        run: npm i serverless -g

      - name: Install dependencies
        run: cd infra/general/ && yarn

      - name: Deploy
        run: cd infra/general/ && serverless deploy --verbose

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}