name: Infra deploy
on:
  pull_request:
  workflow_dispatch:

jobs:
  sls-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.4.1
      - uses: actions/checkout@v2

      - name: Install serverless
        run: npm i serverless -g

      - name: Deploy aurora
        run: cd infra/aurora/ && serverless deploy

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}