name: Test & Deploy
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.4.1
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          # vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          github-comment: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          # working-directory: ./sub-directory