name: Vercel Test & Deploy
on:
  push:
    paths:
      - 'infra/app/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.4.1
      - uses: actions/checkout@v2

      - name: Install
        run: cd app && npm install

      - name: Test
        run: cd app && npm run test
  deployVercel:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          github-comment: "true"
          github-token: ${{ secrets.GH_TOKEN }} #Optional 
          working-directory: ./app